# Generated by Django 4.2.20 on 2026-01-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_project_options_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('collector', 'Collector'), ('gallery', 'Gallery')], default='artist', max_length=20),
        ),
    ]
