# Generated by Django 4.2.20 on 2026-01-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('none', 'No budget'), ('self', 'Self-funded'), ('grant', 'Grant-funded'), ('seeking', 'Seeking funding'), ('commissioned', 'Commissioned')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('development', 'In development'), ('completed', 'Completed'), ('paused', 'Paused')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='manifestations',
            field=models.ManyToManyField(blank=True, to='social.manifestation'),
        ),
    ]
