# Generated by Django 4.2.20 on 2026-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_projectphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
