# Generated by Django 4.2.20 on 2026-01-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_discipline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
