# Generated by Django 4.2.20 on 2026-01-23 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_delete_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='social.project')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
